using System;

namespace QRCoder.Core
{
    /// <summary>
    /// AbstractQRCode
    /// </summary>
    public abstract class AbstractQRCode : IDisposable
    {
        /// <summary>
        /// QRCodeData
        /// </summary>
        protected QRCodeData QrCodeData { get; set; }

        /// <summary>
        /// AbstractQRCode
        /// </summary>
        protected AbstractQRCode()
        {
           

            //Role: csharpsquid:S6444
            //https://sonarcloud.io/organizations/afonsoft/rules?open=csharpsquid%3AS6444&rule_key=csharpsquid%3AS6444&tab=how_to_fix
            AppDomain.CurrentDomain.SetData("REGEX_DEFAULT_MATCH_TIMEOUT", TimeSpan.FromMilliseconds(500));
        }

        /// <summary>
        /// AbstractQRCode
        /// </summary>
        /// <param name="data"></param>
        protected AbstractQRCode(QRCodeData data) : this()
        {
            this.QrCodeData = data;
        }

        /// <summary>
        /// Set a QRCodeData object that will be used to generate QR code. Used in COM Objects connections
        /// </summary>
        /// <param name="data">Need a QRCodeData object generated by QRCodeGenerator.CreateQrCode()</param>
        public virtual void SetQRCodeData(QRCodeData data)
        {
            this.QrCodeData = data;
        }

        /// <summary>
        /// Dispose
        /// </summary>
        public void Dispose()
        {
            Dispose(true);
        }

        protected virtual void Dispose(bool disposing)
        {
            // Cleanup
            if (disposing)
                this.QrCodeData?.Dispose();
            this.QrCodeData = null;
        }

        ~AbstractQRCode()
        {
            Dispose(false);
        }
    }
}